[workspace]
authors = ["Youssef-Harby <youssef.h@walkthru.lat>"]
channels = ["conda-forge"]
name = "mapserver-parquet"
platforms = ["osx-arm64", "win-64", "linux-64"]
version = "0.1.0"

[tasks]
install-xcaddy = "go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest"
build-caddy = { cmd = "xcaddy build --with github.com/aksdb/caddy-cgi/v2", depends-on = ["install-xcaddy"] }

# Cross-platform serve task - pixi auto-detects platform
serve = { depends-on = ["build-caddy"] }

# Platform-specific serve tasks (auto-detected by pixi)
[target.win-64.tasks]
serve = "./caddy run --config ./Caddyfile.windows"

[target.linux-64.tasks]
serve = "./caddy run --config ./Caddyfile.unix"

[target.osx-arm64.tasks]
serve = "./caddy run --config ./Caddyfile.unix"

[dependencies]
gdal = ">=3.11.4,<4"
mapserver = ">=8.4.1,<9"
libgdal-arrow-parquet = ">=3.11.4,<4"
go = ">=1.25.1,<2"
