[workspace]
authors = ["Youssef-Harby <youssef.h@walkthru.lat>"]
channels = ["conda-forge"]
name = "mapserver-parquet"
platforms = ["osx-arm64", "win-64", "linux-64"]
version = "0.1.0"

[tasks]
install-xcaddy = "go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest"
build-caddy = { cmd = "xcaddy build --with github.com/walkthru-lat/caddy-cgi/v2@main", depends-on = ["install-xcaddy"] }
serve = { cmd = "./caddy run --config ./Caddyfile", env = { MAPSERV_EXECUTABLE = ".pixi/envs/default/bin/mapserv" } }
auth-server = { cmd = "cd auth && go run auth_server.go" }


[dependencies]
gdal = ">=3.11.4,<4"
mapserver = ">=8.4.1,<9"
libgdal-arrow-parquet = ">=3.11.4,<4"
go = ">=1.25.1,<2"
